### ISSUE TITLE
Fill out Journal

### ISSUE THREAD

**Issue by jmbott** [jmbott/sofiadeguzman#2]
Add all old pictures w/ descriptions

**Comment by jmbott** [comment]
No old pictures. Link to previous work. Fresh start.

**Comment by jmbott** [comment]
Add new functions: Notes, Galleries, etc?

**Comment by Sofiadeg** [comment]
Sofia is creating a dropbox folder with images to continue adding to journal

**Comment by Sofiadeg** [comment]
Next post: please add a link to the picture magazine website

**Comment by jmbott** [comment]
Added
See commit 781fbedd9488ad4564fbbcda45b1844ab9f12751
And the one before it.
